{
 "title": "HomeMonitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Speedtest by Ookla ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "speedtest_network_download", "legendFormat": "Download MB/s" },
    { "expr": "speedtest_network_upload", "legendFormat": "Upload MB/s" }
   ]
  },
  {
   "title": "Download Mb/s",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_network_download" }
   ]
  },
  {
   "title": "Upload Mb/s",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_network_upload" }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_network_latency" }
   ]
  },
  {
   "title": "Jitter",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_network_jitter" }
   ]
  },
  {
   "title": "Packet Lost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_network_packetLost" }
   ]
  }
 ]
}