global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: speedtest-ookla
    scrape_interval: 30m
    scrape_timeout: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'speedtest-ookla:9000'

  - job_name: grafana
    static_configs:
      - targets:
          - 'grafana:3000'